[book]
title = "Example book"
authors = ["John Doe"]
description = "The example book covers examples."
src = "book"

[rust]
edition = "2021"

[build]
build-dir = "docs"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html.search]
limit-results = 15
