[book]
title = "Astray"
authors = ["Luís Gil"]
description = "Documentation for Astray, an effortless parser builder"
src = "book"

[rust]
edition = "2021"

[build]
build-dir = "docs"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html.search]
limit-results = 15
