[package]
name = "astray_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astray_core = "^1"
astray_macro = "^1"
